---
title: "dts.quality Package"
author: "Lee Kennedy"
date: "May 18th, 2016"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## combo

This function takes a data frame of figures such as might be presented for an ANOVA analysis and creates all possible repeatability and reproducibility combinations, labelled as such.  It drops the column headers..

```{r, echo=FALSE}
A <- c(2,4,3,3)
B <- c(2,3,5,2)
C <- c(1,1,5,2)
D <- c(2,3,2,2)
E <- c(2,3,3,4)
x <- data.frame(A,B,C,D,E)
print(x, row.names = FALSE)
```


**Usage**: with a data file named "df": **combo(df)**

## dupes

This function takes a data frame and reduces it to just the rows that have been duplicated.  When more than one column is nominated, all columns must match.

**Usage**: 

+  with a data file named "df" and column "A": **dupes(df, c("A"))**
+  with a data file named "df" and columns "A" and "D": **dupes(df, c("A", "D"))**

## horwitz

This function calculates the estimated Horwitz value for a given concentration.

**Usage**: with a value named "x": **horwitx(x,n)** when n is the factor to reduce the result to g/g.  n = 2 for g/100g, 6 for mg/kg. 


## outliers

This function identifies outliers in a list of data points.

**Usage**: with a list named "x": **outliers(x,b)** where b is to optionally display boxplots.  By default it equals FALSE.

## TCAR

This function takes a LIMS extract (as a data frame) and rearranges it to look at the components in the Total Carbohydrate calculation.

The items extracted from LIMS are:

Group    |   Sub-Item
---------|-------------
SAMPLE   | SAMPLE_NUMBER
TEST     | ANALYSIS
RESULT   | REPORTED_NAME
RESULT   | REPORTED_UNITS
RESULT   | REPORTED_VALUE
RESULT   | ENTRY
RESULT   | REPORTABLE
RESULT   | ENTERED_BY

**Usage**: with a dataframe extracted for the above parameters, named "x": **TCAR(x)** 

## TOST

This function examines two data sets and estimates whether they are equivalent, allowing for a (nominated) acceptable difference, E..

Ho = the two sets are different. (The revers to the normal Ho.)
H1 = the two sets are equivalent, being no more than epsilon apart.
"Not rejected" means that we have not proven that the two sets are equivalent.
"Rejected" means that there is enough evidence to say that the sets are equivalent, when we accept that equivalence is no more than 'epsilon' apart.

**Usage**: with two data sets, "A" and "B" and a proposed acceptable difference, "E".: **TOST(A, B, E, b)** where b is to optionally display boxplots.  By default it equals FALSE.

## weekly_list

This function takes a file, x, that is equal to the Kanbanchi export file "LK_Projects_full.csv", reconfigures it and exports it in table format to the current woring directory.

**Usage**: for the weekly meeting.


----

